apiVersion: v1
kind: Pod
metadata:
  name: pocket-test-pod
  labels:
    app: pocket-test-pod
spec:
  volumes:
  - name: pocket-volume
    hostPath:
      path: /tmp
  - name: nginx-conf
    configMap:
       name: nginx-config
  containers:
  - name: db
    image: mysql:5.7
    env:
    - name: MYSQL_USER
      value: "wordpress_user"
    - name: MYSQL_ROOT_PASSWORD
      value: "pass"
    - name: MYSQL_PASSWORD
      value: "password"
    - name: MYSQL_DATABASE
      value: "wordpress"
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: pocket-volume
      subPath: mysql
  - name: wordpress
    image: wordpress:5.3.1-php7.2-apache
    env:
    - name: WORDPRESS_DB_USER
      value: "wordpress_user"
    - name: WORDPRESS_DB_HOST
      value: "127.0.0.1"
    - name: WORDPRESS_DB_PASSWORD
      value: "password"
    - name: WORDPRESS_DB_NAME
      value: "wordpress"
    volumeMounts:
    - mountPath: /var/www/html
      name: pocket-volume
      subPath: html
  - name: nginx
    image: nginx
    ports:
    - containerPort: 8080
    volumeMounts:
    - mountPath: /etc/nginx/conf.d/
      name: nginx-conf