apiVersion: v1
kind: Pod
metadata:
  name: mc1
spec:
  volumes:
  - name: wordpress
    hostPath:
      path: /tmp/wordpress
  - name: db
    hostPath:
      path: /tmp/db
  containers:
  - name: nginx
    ports:
      - 
    image: nginx
    volumeMounts:
    di

    
  - name: db
    image: mysql:5.7
    volumeMounts:
    - name: html
      mountPath: /html
    args:
      - while true; do
          date >> /html/index.html;
          sleep 1;
        done
  - name: wordpress
    image: wordpress:5.3.1-php7.2-apache
    volumeMounts:
    - name: wordpress
      mountPath: /html
    command: ["/bin/sh", "-c"]
    args:
      - while true; do
          date >> /html/index.html;
          sleep 1;
        done